#!/bin/sh

FILE=sample/dante.txt

SUM=`cat $FILE | md5sum | sed 's/ *-//g'`

OUT=`cat $FILE | node gzip.js | gunzip | md5sum | sed 's/ *-//g'`
if [ $OUT != $SUM ]
	then
	echo "bad checksum on gzip.js | gunzip"
	exit 1
fi

OUT=`cat $FILE | node gzip.js | node gunzip.js | md5sum | sed 's/ *-//g'`
if [ $OUT != $SUM ]
	then
	echo "bad checksum on gzip.js | gunzip.js"
	exit 1
fi

for c in `seq 1 9`
do
	OUT=`cat $FILE | gzip -$c | node gunzip.js | md5sum | sed 's/ *-//g'`
	if [ $OUT != $SUM ]
		then
		echo "bad checksum on gzip | gunzip.js"
		exit 1
	fi
done

